### ISSUE TITLE
Uncaught Error: Class 'OCA\Files_Antivirus\Db\Rule' not found

### ISSUE THREAD

**Issue by rolandu** [nextcloud/files_antivirus#137]
### Steps to reproduce
1. Install antivirus scanner
2. Upload eicar file (via sync app or directly in browser)

### Expected behaviour
File should be deleted (I configured to delete infected files)

### Actual behaviour
An error is logged

### Server configuration

**Operating system**: Debian 10

**Web server:** Apache 2.0

**Database:** mysql  Ver 15.1 Distrib 10.3.17-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

**PHP version:** 7.3.11-1~deb10u1

**Nextcloud version:** 15.0.11

**Where did you install Nextcloud from:** Download / auto-updater

**List of activated apps:**

```
Enabled:
  - accessibility: 1.1.0
  - activity: 2.8.2
  - admin_audit: 1.5.0
  - calendar: 1.6.6
  - checksum: 0.4.3
  - cloud_federation_api: 0.1.0
  - comments: 1.5.0
  - contacts: 3.1.6
  - dav: 1.8.2
  - encryption: 2.3.0
  - federatedfilesharing: 1.5.0
  - federation: 1.5.0
  - files: 1.10.0
  - files_antivirus: 2.2.0
  - files_pdfviewer: 1.4.0
  - files_sharing: 1.7.0
  - files_texteditor: 2.7.0
  - files_trashbin: 1.5.0
  - files_versions: 1.8.0
  - files_videoplayer: 1.4.0
  - firstrunwizard: 2.4.0
  - gallery: 18.2.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.3.0
  - nextcloud_announcements: 1.4.0
  - notes: 3.0.3
  - notifications: 2.3.0
  - oauth2: 1.3.0
  - password_policy: 1.5.0
  - provisioning_api: 1.5.0
  - serverinfo: 1.5.0
  - sharebymail: 1.5.0
  - support: 1.0.0
  - survey_client: 1.3.0
  - systemtags: 1.5.0
  - theming: 1.6.0
  - twofactor_backupcodes: 1.4.1
  - updatenotification: 1.5.0
  - workflowengine: 1.5.0
Disabled:
  - files_external
  - files_locking
  - files_videoviewer
  - user_ldap
  - user_webdavauth
```

**Clamav version:** 0.101.4+dfsg-0+deb10u1

**Nextcloud configuration:**

```
{
    "system": {
        "maintenance": false,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***mydomain.com***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "15.0.11.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "overwritehost": "***mydomain.com***:4567",
        "overwriteprotocol": "https",
        "overwritewebroot": "\/***path***",
        "overwrite.cli.url": "https:\/\/***mydomain.com***:4567\/***path***",
        "forcessl": true,
        "trashbin_retention_obligation": "7, 30",
        "versions_retention_obligation": "7, auto",
        "log_type": "file",
        "loglevel": 2,
        "log_rotate_size": 10485760,
        "theme": "",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "appstoreenabled": true,
        "appstoreurl": "https:\/\/api.owncloud.com\/v1",
        "appstore.experimental.enabled": true,
        "debug": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "ssl",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "updater.release.channel": "production"
    }
}

```

### Client configuration
**Browser:** multiple

**Operating system:** multiple

#### Nextcloud log (data/owncloud.log)
```
Error on browser upload:

{"reqId":"yz86Dkm1maVO0rWYAmLz","level":3,"time":"2019-11-10T12:56:11+00:00","remoteAddr":"194.166.154.25","user":"***user***","app":"PHP","method":"PROPFIND","url":"/***path***/remote.php/dav/files/***user***/(...)/eicarcom2.zip","message":"Uncaught Error: Class 'OCA\\Files_Antivirus\\Db\\Rule' not found in /var/www/owncloud-standalone/apps/files_antivirus/lib/Db/RuleMapper.php:63\nStack trace:\n#0 /var/www/owncloud-standalone/apps/files_antivirus/lib/Status.php(141): OCA\\Files_Antivirus\\Db\\RuleMapper->findAllMatchedByStatus(1)\n#1 /var/www/owncloud-standalone/apps/files_antivirus/lib/Status.php(84): OCA\\Files_Antivirus\\Status->getResponseRules()\n#2 /var/www/owncloud-standalone/apps/files_antivirus/lib/Scanner/External.php(70): OCA\\Files_Antivirus\\Status->parseResponse('stream: Eicar-T...')\n#3 /var/www/owncloud-standalone/apps/files_antivirus/lib/Scanner/ScannerBase.php(129): OCA\\Files_Antivirus\\Scanner\\External->shutdownScanner()\n#4 /var/www/owncloud-standalone/apps/files_antivirus/lib/AvirWrapper.php(118): OCA\\Files_Antivirus\\Scanner\\ScannerBase->completeAsyncScan()\n#5 [internal function]: OCA\\Files_Antivirus\\AvirWrapper->OCA\\Files_Antivirus\\{closure}()\n#6 /var/www/owncloud-standalone/3rdparty/icewind/streams/src/CallbackWrapper.php(121): call_user_ at /var/www/owncloud-standalone/apps/files_antivirus/lib/Db/RuleMapper.php#63","userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:70.0) Gecko/20100101 Firefox/70.0","version":"15.0.11.1","id":"5dc808eb6b814"}

[PHP] Error: Uncaught Error: Class 'OCA\Files_Antivirus\Db\Rule' not found in /var/www/owncloud-standalone/apps/files_antivirus/lib/Db/RuleMapper.php:63
Stack trace:
#0 /var/www/owncloud-standalone/apps/files_antivirus/lib/Status.php(141): OCA\Files_Antivirus\Db\RuleMapper->findAllMatchedByStatus(1)
#1 /var/www/owncloud-standalone/apps/files_antivirus/lib/Status.php(84): OCA\Files_Antivirus\Status->getResponseRules()
#2 /var/www/owncloud-standalone/apps/files_antivirus/lib/Scanner/External.php(70): OCA\Files_Antivirus\Status->parseResponse('stream: Eicar-T...')
#3 /var/www/owncloud-standalone/apps/files_antivirus/lib/Scanner/ScannerBase.php(129): OCA\Files_Antivirus\Scanner\External->shutdownScanner()
#4 /var/www/owncloud-standalone/apps/files_antivirus/lib/AvirWrapper.php(118): OCA\Files_Antivirus\Scanner\ScannerBase->completeAsyncScan()
#5 [internal function]: OCA\Files_Antivirus\AvirWrapper->OCA\Files_Antivirus\{closure}()
#6 /var/www/owncloud-standalone/3rdparty/icewind/streams/src/CallbackWrapper.php(121): call_user_ at /var/www/owncloud-standalone/apps/files_antivirus/lib/Db/RuleMapper.php#63

PROPFIND /***path***/remote.php/dav/files/***user***/(...)/eicarcom2.zip
from 194.166.154.25 by ***user*** at 2019-11-10T12:56:11+00:00

Error on sync app upload:

{"reqId":"b1kz8PA5nIAhmDvzebpv","level":3,"time":"2019-11-10T13:05:44+00:00","remoteAddr":"194.166.154.25","user":"***user***","app":"PHP","method":"GET","url":"/***path***/ocs/v2.php/apps/notifications/api/v2/notifications","message":"Uncaught Error: Class 'OCA\\Files_Antivirus\\Db\\Rule' not found in /var/www/owncloud-standalone/apps/files_antivirus/lib/Db/RuleMapper.php:63\nStack trace:\n#0 /var/www/owncloud-standalone/apps/files_antivirus/lib/Status.php(141): OCA\\Files_Antivirus\\Db\\RuleMapper->findAllMatchedByStatus(1)\n#1 /var/www/owncloud-standalone/apps/files_antivirus/lib/Status.php(84): OCA\\Files_Antivirus\\Status->getResponseRules()\n#2 /var/www/owncloud-standalone/apps/files_antivirus/lib/Scanner/External.php(70): OCA\\Files_Antivirus\\Status->parseResponse('stream: Eicar-T...')\n#3 /var/www/owncloud-standalone/apps/files_antivirus/lib/Scanner/ScannerBase.php(129): OCA\\Files_Antivirus\\Scanner\\External->shutdownScanner()\n#4 /var/www/owncloud-standalone/apps/files_antivirus/lib/AvirWrapper.php(118): OCA\\Files_Antivirus\\Scanner\\ScannerBase->completeAsyncScan()\n#5 [internal function]: OCA\\Files_Antivirus\\AvirWrapper->OCA\\Files_Antivirus\\{closure}()\n#6 /var/www/owncloud-standalone/3rdparty/icewind/streams/src/CallbackWrapper.php(121): call_user_ at /var/www/owncloud-standalone/apps/files_antivirus/lib/Db/RuleMapper.php#63","userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:70.0) Gecko/20100101 Firefox/70.0","version":"15.0.11.1","id":"5dc80b28ea9e4"}


[PHP] Error: Uncaught Error: Class 'OCA\Files_Antivirus\Db\Rule' not found in /var/www/owncloud-standalone/apps/files_antivirus/lib/Db/RuleMapper.php:63
Stack trace:
#0 /var/www/owncloud-standalone/apps/files_antivirus/lib/Status.php(141): OCA\Files_Antivirus\Db\RuleMapper->findAllMatchedByStatus(1)
#1 /var/www/owncloud-standalone/apps/files_antivirus/lib/Status.php(84): OCA\Files_Antivirus\Status->getResponseRules()
#2 /var/www/owncloud-standalone/apps/files_antivirus/lib/Scanner/External.php(70): OCA\Files_Antivirus\Status->parseResponse('stream: Eicar-T...')
#3 /var/www/owncloud-standalone/apps/files_antivirus/lib/Scanner/ScannerBase.php(129): OCA\Files_Antivirus\Scanner\External->shutdownScanner()
#4 /var/www/owncloud-standalone/apps/files_antivirus/lib/AvirWrapper.php(118): OCA\Files_Antivirus\Scanner\ScannerBase->completeAsyncScan()
#5 [internal function]: OCA\Files_Antivirus\AvirWrapper->OCA\Files_Antivirus\{closure}()
#6 /var/www/owncloud-standalone/3rdparty/icewind/streams/src/CallbackWrapper.php(121): call_user_ at /var/www/owncloud-standalone/apps/files_antivirus/lib/Db/RuleMapper.php#63

GET /***path***/ocs/v2.php/apps/notifications/api/v2/notifications
from 194.166.154.25 by ***user*** at 2019-11-10T13:05:44+00:00
```

#### Browser log
N/A

**Comment by jkoopmann** [comment]
I see the same issue with the latest version:

`Uncaught Error: Class 'OCA\Files_Antivirus\Db\Rule' not found in /usr/local/www/nextcloud/apps/files_antivirus/lib/Db/RuleMapper.php:63 Stack trace: #0 /usr/local/www/nextcloud/apps/files_antivirus/lib/Status.php(141): OCA\Files_Antivirus\Db\RuleMapper->findAllMatchedByStatus(1) #1 /usr/local/www/nextcloud/apps/files_antivirus/lib/Status.php(84): OCA\Files_Antivirus\Status->getResponseRules() #2 /usr/local/www/nextcloud/apps/files_antivirus/lib/Scanner/External.php(70): OCA\Files_Antivirus\Status->parseResponse('stream: OK\n') #3 /usr/local/www/nextcloud/apps/files_antivirus/lib/Scanner/ScannerBase.php(129): OCA\Files_Antivirus\Scanner\External->shutdownScanner() #4 /usr/local/www/nextcloud/apps/files_antivirus/lib/AvirWrapper.php(118): OCA\Files_Antivirus\Scanner\ScannerBase->completeAsyncScan() #5 [internal function]: OCA\Files_Antivirus\AvirWrapper->OCA\Files_Antivirus\{closure}() #6 /usr/local/www/nextcloud/apps/files_external/3rdparty/icewind/streams/src/CallbackWrapper.php(121): call_user_func(Object(Cl at /usr/local/www/nextcloud/apps/files_antivirus/lib/Db/RuleMapper.php#63 `

**Comment by kesselb** [comment]
Thanks for your report :+1: 

This case should be fixed by https://github.com/nextcloud/server/pull/28907. It's still in review but is hopefully shipped with one of the next releases.
