### ISSUE TITLE
file size is not obeyed

### ISSUE THREAD

**Issue by individual-it** [nextcloud/files_antivirus#92]
### Steps to reproduce
1. set up the app with file size 100bytes
![image](https://user-images.githubusercontent.com/2425577/42985094-a913566c-8c0f-11e8-8e5c-db5f22dde5ab.png)
2. get eicar test files from https://www.eicar.org/85-0-Download.html
3. try to upload `eicar_com.zip`184 Bytes or `eicarcom2.zip` 308 Bytes

### Expected behaviour
upload should work as the files are bigger than the set file size

### Actual behaviour
upload rejected

### Server configuration

**Operating system**:
Ubuntu 18.04

**Web server:**
apache

**Database:**
sqlite

**PHP version:**
7.2

**Nextcloud version:** (see Nextcloud admin page)
13.0.4

**Where did you install Nextcloud from:**
nextcloud.com

**List of activated apps:**

```
Enabled:
  - activity: 2.6.1
  - comments: 1.3.0
  - dav: 1.4.7
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_antivirus: 1.3.1
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - firstrunwizard: 2.2.1
  - gallery: 18.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - nextcloud_announcements: 1.2.0
  - notifications: 2.1.2
  - oauth2: 1.1.1
  - password_policy: 1.3.0
  - provisioning_api: 1.3.0
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - survey_client: 1.1.0
  - systemtags: 1.3.0
  - theming: 1.4.5
  - twofactor_backupcodes: 1.2.3
  - updatenotification: 1.3.0
  - workflowengine: 1.3.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - files_pdfviewer
  - user_external
  - user_ldap
```

**Nextcloud configuration:**

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "http:\/\/localhost\/nextcloud",
        "dbtype": "sqlite3",
        "version": "13.0.4.0",
        "installed": true
    }
}
```

### Client configuration
**Browser:**
Firefox 61

**Operating system:**
Ubuntu 18.04

#### Nextcloud log (data/owncloud.log)
```
{"reqId":"JNoqyDUktL6gnob2sSJU","level":4,"time":"2018-07-20T05:45:33+00:00","remoteAddr":"127.0.0.1","user":"admin","app":"webdav","method":"PUT","url":"\/nextcloud\/remote.php\/webdav\/eicarcom2.zip","message":"Exception: {\"Exception\":\"OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Exception\\\\UnsupportedMediaType\",\"Message\":\"Virus Eicar-Test-Signature is detected in the file. Upload cannot be completed.\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/artur\\\/www\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php(188): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->convertToSabreException(Object(OCP\\\\Files\\\\InvalidContentException))\\n#1 \\\/home\\\/artur\\\/www\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Directory.php(156): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->put(Resource id #74)\\n#2 \\\/home\\\/artur\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1096): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory->createFile('eicarcom2.zip', Resource id #74)\\n#3 \\\/home\\\/artur\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(529): Sabre\\\\DAV\\\\Server->createFile('eicarcom2.zip', Resource id #74, NULL)\\n#4 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/home\\\/artur\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#6 \\\/home\\\/artur\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#7 \\\/home\\\/artur\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#8 \\\/home\\\/artur\\\/www\\\/nextcloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(80): Sabre\\\\DAV\\\\Server->exec()\\n#9 \\\/home\\\/artur\\\/www\\\/nextcloud\\\/remote.php(164): require_once('\\\/home\\\/artur\\\/www...')\\n#10 {main}\",\"File\":\"\\\/home\\\/artur\\\/www\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php\",\"Line\":568}","userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:61.0) Gecko\/20100101 Firefox\/61.0","version":"13.0.4.0"}

```

**Comment by rullzer** [comment]
Fixed in #99
